name: Build IPA for AltStore with xcodeproj

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14 # Xcode 15.4 포함

    steps:
      # 1. 리포지토리 체크아웃
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Xcode 버전 선택
      - name: Select Xcode Version
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      # 3. project.pbxproj에서 서명 및 아키텍처 설정 제거
      - name: Update project.pbxproj
        run: |
          sed -i '' '/DEVELOPMENT_TEAM =/d' wkwebview.xcodeproj/project.pbxproj || true
          sed -i '' 's/CODE_SIGN_STYLE = "[^"]*"/CODE_SIGN_STYLE = None/' wkwebview.xcodeproj/project.pbxproj || true
          sed -i '' 's/ARCHS = "[^"]*"/ARCHS = arm64/' wkwebview.xcodeproj/project.pbxproj || true
          sed -i '' 's/VALID_ARCHS = "[^"]*"/VALID_ARCHS = arm64/' wkwebview.xcodeproj/project.pbxproj || true
          sed -i '' 's/CODE_SIGN_IDENTITY = "[^"]*"/CODE_SIGN_IDENTITY = ""/' wkwebview.xcodeproj/project.pbxproj || true
          sed -i '' 's/PROVISIONING_PROFILE = "[^"]*"/PROVISIONING_PROFILE = ""/' wkwebview.xcodeproj/project.pbxproj || true

      # 4. 프로젝트 빌드 (서명 비활성화)
      - name: Build Project without Signing
        run: |
          xcodebuild \
            -project wkwebview.xcodeproj \
            -scheme wkwebview \
            -configuration Release \
            -archivePath build/wkwebview.xcarchive \
            clean archive \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGN_IDENTITY="" \
            PROVISIONING_PROFILE="" \
            CODE_SIGN_STYLE=None \
            ARCHS=arm64 \
            VALID_ARCHS=arm64 \
            SKIP_INSTALL=NO \
            BUILD_LIBRARY_FOR_DISTRIBUTION=NO

      # 5. .ipa 파일 생성
      - name: Export IPA
        run: |
          cat > exportOptions.plist << 'EOF'
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
            <key>method</key>
            <string>development</string>
            <key>compileBitcode</key>
            <false/>
            <key>signingStyle</key>
            <string>manual</string>
            <key>stripSwiftSymbols</key>
            <false/>
          </dict>
          </plist>
          EOF
          xcodebuild \
            -exportArchive \
            -archivePath build/wkwebview.xcarchive \
            -exportPath build \
            -exportOptionsPlist exportOptions.plist

      # 6. .ipa 파일 아티팩트 업로드
      - name: Upload IPA for AltStore
        uses: actions/upload-artifact@v4
        with:
          name: wkwebview-demo-ipa
          path: build/wkwebview-demo.ipa

      # 7. 정리
      - name: Cleanup
        if: always()
        run: |
          rm -rf build/wkwebview.xcarchive exportOptions.plist